### ISSUE TITLE
Исследовательская

### ISSUE THREAD

**Issue by J0hannex** [J0hannex/ServiceToFixAndSail#1]

**Comment by J0hannex** [comment]
[Задание БД.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5177686/default.docx)
[титульник БД.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5177687/default.docx)

**Comment by J0hannex** [comment]
[ТЗ и исследовательская.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5177689/default.docx)

**Comment by wldmr-key** [comment]
замечания по ТЗ:
Судя по тому, что ты начал писать в предметой области, ты собираешься ни продажи толком смоделировать, ни сервис (просто задача получается большой). Поэтому, советую тебе ограничиться сервисом, но сделать его, как следует.
Обрати внимание, на то, как лучше организовать взаимодействие с клиентом и сделать для него процесс взаимодействия с сервисом наиболее удобным и выгодным
Пожалйста, не используй термин "железо" - кровь из глаз!
По форме ТЗ нормальное, по существу - рассмотри мои замечания

**Comment by J0hannex** [comment]
[ТЗ и исследовательская.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5220131/default.docx)
Исправлено

**Comment by wldmr-key** [comment]
ТЗ стало намного лучше. Только не говори о ремонте сломанной техники. Я ни разу не слышал о ремонте исправной техники (и, кстати, если мы говорим о компьютерном железе, то для него еще есть понятия апгрейда и настройки)
Очень хорошо, что приступил к исследовательской части. Больше будет времени на исправление ошибок.
Например, какой и клиента Id? Что это такое вообще?
Откуда берется цена на СУ? (и, да, бросай ты эти сокращения - копипаст что ли не работает?)
Ну, про нарисованные связи в концептуальной схеме скорбно помолчим... Давай, вспоминай все скорее и исправляйся ))

**Comment by J0hannex** [comment]
[Ислед часть.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5249258/default.docx)

**Comment by wldmr-key** [comment]
При чтении текста создается впечатление, что концептуальная схема данных пришла тебе во сне, как таблица периодических элементов Менделееву. Так как логика ее появления минимаольна. Тест простой - при описании предметной обьласти у тебя должен быть упомянут каждый атрибут и сущность концептуальной модели (возможны исключения - это, как правило, детали, скрывающиеся за словами "и т.п."). У тебя этого нет - и сценарии использования минимальны.
Что такое "клиент заполняет заявку". Свой id он вводит, например? А, откуда он его знает? И так про все (почти) атрибуты...

**Comment by J0hannex** [comment]
[Ислед часть.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5291296/default.docx)

**Comment by wldmr-key** [comment]
Жеотым выделено то, что мне не нравится и еще есть комментарии
[default (4).docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5307977/default.4.docx)

**Comment by J0hannex** [comment]
Я не до конца понимаю, что  надо поменять в задаче автоматизации и в сценарии для админа

**Comment by wldmr-key** [comment]
задача автоматизации - это следствие из описания предметной области. В описании ты рассказываешь про процессы реальной жизни, в задаче ты рассказываешь, какие процессы и как ты автоматизируешь своим приложением. У тебя - все перемешано в общем описании, а задача - формальное предложение
Сценарии должны реализовывать все функции, которые у тебя описаны ранее

**Comment by J0hannex** [comment]
Добавил проект в разделе Code, если все загрузилось правильно, должен работать. Правки по исследовательской части будут позже.

**Comment by wldmr-key** [comment]
ох, боюсь, переделывать еще не раз код придется ))
логической схемы-то еще нет...

**Comment by wldmr-key** [comment]
но, появление собираемого кода само по себе явление похвальное

**Comment by J0hannex** [comment]
[Isled_chast.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5387514/Isled_chast.docx)
Исправил все возможные замечания и выделенные желтым фрагменты. Концептуальная схема пока не исправлена.

**Comment by wldmr-key** [comment]
До концептуальной схемы все очень мило. Концептуальная схема появляется сюрпризно и, как следствие, содержит ошибки и нестыковки. Даже у критикуемых тобой сайтов существует прайс-лист на услуги. У тебя такого нет. Откуда взялась сущность с датами? В тексте нет никакого намека... В стоимость ремонта входят или не входят комплектующие? Что происходит с оплатой? Какие у заказа бывают статусы?
Видимо, необходим анализ предметной области для выяснения этих вопросов.

И, да, для составления сценариев тоже - а то - ужас-ужас.

И, намек - кто, кроме клиента пользуется БД? Как?

**Comment by J0hannex** [comment]
Дополнил предметную область описанием сайта и переделал сценарии использования в графическое представление. Концептуальная схема будет сделана позже после подтверждения описанных данных в предметной области. Из-за болезни временно снизился темп работы.
[Isled_chast.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5441060/Isled_chast.docx)

**Comment by wldmr-key** [comment]
ок, дополнение хорошее, но не совсем верное. Предметная область - это деятельность магазина (и ты ее в некоторых моментах очень правильно дополнил - прайся-лист, статусы заказов, общение с клиентом и т.д.)
А, вот, описание сайта - это уже твоя задача проектирования и разработки. На основании  анализа предметной области ты делаешь выводы об основных функциях, данных и сценариях использования сайта. Чувствуешь разницу? Поэтому все твои правильные слова о будущем сайтк я бы вынес из описания предметной области.
Концептуальная модель выглядит оторванной от твоего классного описания и, поэтому, неправильной
Сценарий использования неправильно составлен. Во первых, графически - посмотри, хоть википедию, что и как там должно рисоваться

**Comment by J0hannex** [comment]
![image](https://user-images.githubusercontent.com/55578293/97353108-a9f45f80-18a4-11eb-9e76-3c77d8a7b89a.png)
Немного переделал концептуальную схему. Насчет схемы использования не понял, примеры из википедии похожи примерно, только не такие вложенные.

**Comment by wldmr-key** [comment]
Похоже, я запутал тебя на своих лекциях с использованием времени. Вот, попробуй, объясни словами сущность "Даты сервсиных услуг". ОБрати внимание - в описании предметной области у тебя про нее явно ничего не говориться! Так, может, ее и нет вовсе? А, есть определенные атрибуты...

Зато у тебя в описании говорится про прайс-лист. А в схеме данных его нет... не настораживает? Каталог услуг у тебя разве простой список? И что у тебя твориться с учетом стоимости комплектующих (я уже не говорю про учет собственно комплектующих)

Про сценарии использования я имел в виду излишнюю вложенность и использование описаний вместо действий

**Comment by J0hannex** [comment]
Я хотел чтобы была дата подачи заявки и дата начала услуг, чтобы клиент заранее мог договориться на нужную ему дату. Индивидуальный подход. Даты могут и совпадать, если клиенту не важно в какую дату начать работу

**Comment by wldmr-key** [comment]
так, почему это не атрибуты заявки?! По твоей картинке получается, наоборот, есть колхозные даты начала и конца, ассоциированные с несколькими заявками. Что это?!

**Comment by J0hannex** [comment]
![image](https://user-images.githubusercontent.com/55578293/97362195-b3d08f80-18b1-11eb-9f70-82d28a1e1468.png)

**Comment by wldmr-key** [comment]
Сильно лучше стало. Но, тебе не кажется, что каталог услуг и прайс-лист - это одно и то же. Услуга не может потребовать более одной комплектующей? Цена заказа всегда складывается из цены прайс-листа и суммы цен комплектующих?

**Comment by J0hannex** [comment]
![image](https://user-images.githubusercontent.com/55578293/97457691-0ca03680-194b-11eb-81f9-0cc5a048a3a1.png)
Названия комплектующих будут записываться в атрибут через запятую, если их несколько. Если их нет, цена за комплектующие 0.

**Comment by wldmr-key** [comment]
> Названия комплектующих будут записываться в атрибут через запятую, если их несколько. Если их нет, цена за комплектующие 0.

Ох!!! я же вам рассказывал про антипаттерны!!! Нельзя так!!!  А, если я поставил в компьютер 4 планки одинаковой памяти или два диска - это через какую запятую записывать?!

**Comment by J0hannex** [comment]
С антипаттернами небольшие проблемы но попробую сделать.

**Comment by J0hannex** [comment]
Концептуальная схема сама по себе правильная? Хотя бы по сущностям. Для решения вопроса с антипаттернами в логической схеме будет создана дополнительная таблица где будет писать id услуги, id детали и количество.

**Comment by J0hannex** [comment]
![image](https://user-images.githubusercontent.com/55578293/98261067-19e5a280-1f95-11eb-80de-40a18d1af485.png)
Немного поменял схему, но все также небольшие неуверенности касательно связей.

**Comment by wldmr-key** [comment]
Ох! Ну, зачем "будет создана",если в самой природе есть очевидная сущность - "Деталь в заказе" у которой единственный атрибут - количество и которая связана с заказом и с деталями. Зачем ты комплектующие раззбомбил на две части? Зачем опять появился каталог, если есть прайс-лист?

**Comment by J0hannex** [comment]
![Screenshot_20201106_001655](https://user-images.githubusercontent.com/55578293/98297502-8f696700-1fc5-11eb-8549-6544c4960fdf.jpg)
Исправлено

**Comment by wldmr-key** [comment]
Обрати внимание: "если в самой природе есть очевидная сущность - "Деталь в заказе" у которой единственный атрибут - количество и которая **связана с заказом и с деталями**."

**Comment by J0hannex** [comment]
![Screenshot_20201106_121359](https://user-images.githubusercontent.com/55578293/98348319-a2158780-2029-11eb-8c8e-d7f6f9cb79c8.jpg)
Не совсем понял, нужна ли дополнительная сущность с названием комплектующие?

**Comment by J0hannex** [comment]
Немного начал конструкторскую часть
[конструкторская.docx](https://github.com/J0hannex/ServiceToFixAndSail/files/5505402/default.docx)

**Comment by wldmr-key** [comment]
Еще раз про концептуальную схему: Обрати внимание на выделение шрифтом )): "если в самой природе есть очевидная сущность - "Деталь в заказе" у которой единственный атрибут - количество и которая **связана с заказом и с деталями**."

Конструкторская часть -[ отдельная задача](https://github.com/J0hannex/ServiceToFixAndSail/issues/2), не нужно все валить в одну кучу

**Comment by J0hannex** [comment]
Детали это тоже будет новая сущность, которая будет включать в себя весь список комплектующих?

**Comment by wldmr-key** [comment]
Комплектующие - например, "Задний левый диодный фонарь LADA Granta (Лада Гранта) ZFT-310LED (задняя фара)" по цене 2290 руб 6 штук на складе
Заказ для Кириллова В.Ю. - выправить бампер и поставить на его ладу новую левую фару
Два и да сложим? ))

**Comment by J0hannex** [comment]
![Screenshot_20201108_233943](https://user-images.githubusercontent.com/55578293/98483714-b91bcb80-221b-11eb-9b02-56a53424e84b.jpg)

**Comment by wldmr-key** [comment]
и со стрелками еще бы разобраться

**Comment by J0hannex** [comment]
А со сущностями и их атрибутами все хорошо?

**Comment by wldmr-key** [comment]
во всяком случае, гораздо лучше, чем было ))

**Comment by J0hannex** [comment]
Со стрелками небольшие сложности, не совсем понял что нужно изменить. Виды некоторых связей?

**Comment by wldmr-key** [comment]
что за связь между комплектующими и заказами?

Следующие утверждения следуют из твоих стрелок. Они все правильны?
У клиента может быть много заказов. Верно?
В заказе может быть только одна услуга? Верно?
Деталь заказа описывает одну комплектующую. Верно?
Деталь заказа может входить во много заказов. Верно?

**Comment by J0hannex** [comment]
![image](https://user-images.githubusercontent.com/55578293/99069143-d99ea980-25be-11eb-99fa-1961962951dc.png)
У клиентов может быть много заказов. Пока будет ограничение по 1 услуге на заказ. Деталь заказа, по идее, входит в один заказ.  Со связью деталь заказа и комплектующие пока сложности, по идее если заказывать, у комплектующих может быть много деталей в заказе.

**Comment by wldmr-key** [comment]
ты сложности сам себе придумываешь! ))

`что за связь между комплектующими и заказами?` - было намеком. Такой прямой связи нет.

Деталь в заказе - это сущность, которая ассоциируется  (а) с одной из комплектующих и (б) с одним из заказов и содержит количество определенной комплектующей в определенном заказе

**Comment by J0hannex** [comment]
![image](https://user-images.githubusercontent.com/55578293/99070695-c80ad100-25c1-11eb-9b9a-e1bed28f11c3.png)
меня просто смутило одно поле в сущности "деталь в заказе", в логической  я предполагаю у нее id будет вторичный ключ от ключа сущности Комплектующие

**Comment by wldmr-key** [comment]
направление одной из связей осталось неправильным - найдешь?

**Comment by J0hannex** [comment]
![image](https://user-images.githubusercontent.com/55578293/99077957-a106cc00-25ce-11eb-8233-3f0f071efb93.png)
Я так понял у деталей в заказе не может быть несколько других комплектующих, но у комплектующих может быть несколько деталей в заказе и следовательно они могут быть во многих заказах

**Comment by J0hannex** [comment]
![image](https://user-images.githubusercontent.com/55578293/99107356-c4de0800-25f6-11eb-9f99-2e623581f0f4.png)
![image](https://user-images.githubusercontent.com/55578293/99108293-310d3b80-25f8-11eb-8f5a-cce68027cfe2.png)
Поменял сценарии использования

**Comment by wldmr-key** [comment]
> Я так понял у деталей в заказе не может быть несколько других комплектующих, но у комплектующих может быть несколько деталей в заказе и следовательно они могут быть во многих заказах
мысль изложена безобразно, но нарисовано правильно

**Comment by wldmr-key** [comment]
> Поменял сценарии использования

ну, можно и так. Подробная детализация - не в моем вкусе, но, если ты считаешь, что так хорошо...

**Comment by J0hannex** [comment]
Про детали в заказе хотел сказать, что в одной детали заказа может комплектующая только одного вида, но не обязательно в единичном экземпляре. А один вид комплектующих может быть в различных заказах. 
С исследовательской частью тогда работа закончена, теперь все силы на доработку кода и конструкторскую часть.
